title: Chris Look
email: lookwchristopher@gmail.com
github_username: lookcw

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
  - video-call-calendar-auto-call.md
  - open-calendar-slots.md
