source "https://rubygems.org"

gem "minima", "~> 2.0"
gem "github-pages", "~> 228", group: :jekyll_plugins
gem "kramdown-parser-gfm"
gem "webrick", "~> 1.8"
gem "csv"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-redirect-from"
end
